import React from 'react';

const MatchResult = ({ result }) => {
  const { analysis } = result;
  
  const getScoreColor = (score) => {
    if (score >= 80) return '#28a745'; // Green
    if (score >= 60) return '#ffc107'; // Yellow
    if (score >= 40) return '#fd7e14'; // Orange
    return '#dc3545'; // Red
  };

  const getScoreEmoji = (score) => {
    if (score >= 80) return '🎉';
    if (score >= 60) return '👍';
    if (score >= 40) return '⚠️';
    return '🔴';
  };

  const getScoreDescription = (score) => {
    if (score >= 80) return 'Excellent Match';
    if (score >= 60) return 'Good Match';
    if (score >= 40) return 'Fair Match';
    return 'Needs Improvement';
  };

  return (
    <div className="match-result">
      <h2>📊 Analysis Results</h2>
      
      {/* Match Score Section */}
      <div className="score-section">
        <div className="score-card">
          <div className="score-header">
            <h3>Match Score</h3>
          </div>
          <div className="score-display">
            <div 
              className="score-circle"
              style={{ borderColor: getScoreColor(analysis.match_score) }}
            >
              <span className="score-number" style={{ color: getScoreColor(analysis.match_score) }}>
                {analysis.match_score}%
              </span>
            </div>
            <div className="score-info">
              <span className="score-emoji">{getScoreEmoji(analysis.match_score)}</span>
              <span 
                className="score-description"
                style={{ color: getScoreColor(analysis.match_score) }}
              >
                {getScoreDescription(analysis.match_score)}
              </span>
            </div>
          </div>
        </div>
      </div>

      {/* Missing Keywords Section */}
      <div className="keywords-section">
        <div className="section-card">
          <h3>🔍 Missing Keywords</h3>
          <p className="section-description">
            Add these keywords from the job description to improve your resume's relevance:
          </p>
          <div className="keywords-grid">
            {analysis.missing_keywords.map((keyword, index) => (
              <span key={index} className="keyword-tag">
                {keyword}
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* Suggestions Section */}
      <div className="suggestions-section">
        <div className="section-card">
          <h3>💡 Improvement Suggestions</h3>
          <p className="section-description">
            Here are specific ways to enhance your resume for this position:
          </p>
          <div className="suggestions-list">
            {analysis.suggestions.map((suggestion, index) => (
              <div key={index} className="suggestion-item">
                <span className="suggestion-number">{index + 1}</span>
                <span className="suggestion-text">{suggestion}</span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Action Items Section */}
      <div className="action-section">
        <div className="section-card">
          <h3>🎯 Next Steps</h3>
          <div className="action-list">
            <div className="action-item">
              <span className="action-icon">📝</span>
              <span>Incorporate the missing keywords naturally into your resume</span>
            </div>
            <div className="action-item">
              <span className="action-icon">🔄</span>
              <span>Update your resume and reanalyze to track improvement</span>
            </div>
            <div className="action-item">
              <span className="action-icon">📋</span>
              <span>Tailor your cover letter to address the job requirements</span>
            </div>
            <div className="action-item">
              <span className="action-icon">🎉</span>
              <span>Apply with confidence once you've optimized your resume</span>
            </div>
          </div>
        </div>
      </div>

      {/* Export/Share Options */}
      <div className="export-section">
        <div className="export-buttons">
          <button 
            className="export-btn"
            onClick={() => {
              const resultText = `
                    Resume Match Analysis Results
                    ============================

                    Match Score: ${analysis.match_score}% (${getScoreDescription(analysis.match_score)})

                    Missing Keywords:
                    ${analysis.missing_keywords.map(k => `• ${k}`).join('\n')}

                    Improvement Suggestions:
                    ${analysis.suggestions.map((s, i) => `${i + 1}. ${s}`).join('\n')}

                    Generated by Resume Matcher
                    `;
              navigator.clipboard.writeText(resultText);
              alert('Results copied to clipboard!');
            }}
          >
            📋 Copy Results
          </button>
          
          {/* <button 
            className="export-btn"
            onClick={() => {
              const dataStr = JSON.stringify(analysis, null, 2);
              const dataBlob = new Blob([dataStr], { type: 'application/json' });
              const url = URL.createObjectURL(dataBlob);
              const link = document.createElement('a');
              link.href = url;
              link.download = 'resume-analysis.json';
              link.click();
              URL.revokeObjectURL(url);
            }}
          >
            💾 Download JSON
          </button> */}
        </div>
      </div>
    </div>
  );
};

export default MatchResult;